variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test
  - package

build:
  stage: build
  tags:
    - htpc
  script:
    - ./generate.sh
    - ./configure.sh
    - ./build.sh 8
  cache:
    policy: push
    paths:
      - build

test:
  stage: test
  tags:
    - htpc
  script:
    - ./test.sh
  dependencies:
    - build
  cache:
    policy: pull
    paths:
      - build

package:
  stage: package
  tags:
    - htpc
  script:
    - ./package.sh
  dependencies:
    - test
  cache:
    policy: pull
    paths:
      - build
